### PR TITLE
Add remote option to wmi input.

### PR DESCRIPTION
**Pull request by ThomasdOtreppe**
Issue #7 and #2

### CODE REVIEW

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by ThomasdOtreppe** [comment]
Do you have any update? Btw, I signed the CLA a long time ago and we cleared that up in https://github.com/elastic/logstash/pull/3645#issuecomment-125320385

**Comment by rbclark** [comment]
Any chance this could be looked into again? I just found myself looking for this exact functionality only to discover that it is so close to being available and is just waiting on a merge.

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by jsvd** [comment]
@ThomasdOtreppe sorry I haven't gotten around to test this on my windows laptop.
I'll try to check this next week

**Comment by ThomasdOtreppe** [comment]
It shouldn't need any testing (other than the github check to see if it merges correctly) since it was some code that was already in the plugin but was lost when moving each plugin in their own repository.

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by ThomasdOtreppe** [comment]
Any update?

**Comment by suyograo** [comment]
@ThomasdOtreppe really sorry for the delay here. I published v2.0.5 with these changes

**Pull request merged**
